// import Link from "next/link";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//         <Link href="/">Home</Link>
//         {children}
//       </body>
//     </html>
//   );
// }

import Link from "next/link";
import Image from "next/image";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={styles.body}>
        <header style={styles.header}>
          <Link href="/" style={styles.link}>
            <Image 
              src="/HomeButton.png" 
              alt="Description of image" 
              width={50} 
              height={50} 
              style={styles.image}
            />
          </Link>
        </header>
        <main style={styles.main}>
          
          {children}
        </main>
      </body>
    </html>
  );
}

const styles = {
  body: {
    fontFamily: 'Arial, sans-serif',
    margin: 0,
    padding: 0,
    backgroundColor: '#f4f4f4',
  },
  header: {
    // backgroundColor: '#333',
    padding: '1rem',
  },
  link: {
    color: '#fff',
    textDecoration: 'none',
    fontSize: '1.2rem',
  },
  main: {
    padding: '2rem',
  },
  image: {
    display: 'block',
    margin: '0 auto 2rem',
    borderRadius: '8px',
  }
};
